### ISSUE TITLE
change to the path update code necessary to make it work correctly

### ISSUE THREAD

**Issue by sadaszewski** [maxtmng/shortest_path_turn_penalty#1]
I find the following change to the path update code necessary to make it work correctly.

```python
if u in paths and len(paths[u]) > 1:
    if vu_dist < seen[paths[u][-2]][paths[u][-1]]:
        paths[u] = paths[v] + [u]
else:
    paths[u] = paths[v] + [u]
```

**Comment by maxtmng** [comment]
Hi @sadaszewski , thank you for your contribution! Also sorry for the delay in reply.
I studied your [code](https://github.com/sadaszewski/shortest_path_turn_penalty/) and tested with some test cases. It seems that the results are similar before and after the changes, except that there is a redundant node added at the end.
To aid testing, I uploaded a [testing method](https://github.com/maxtmng/shortest_path_turn_penalty/blob/main/test_shortest_path_turn_penalty.py) with a simple graph.
If similar errors still happen to your use case, would you please share more details (e.g., network, penalty, test nodes) so I can try to replicate it on my side?
