### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'in_edges'

### ISSUE THREAD

**Issue by MattCremeens** [maxtmng/shortest_path_turn_penalty#2]
I'm getting the above error. Has this maybe been deprecated in Networkx?

**Comment by maxtmng** [comment]
Thanks for raising this. It seems the issue is related to G as an undirected graph. I have updated the codes to cover that as well. If G is expected to be an undirected graph, please see if it works now.

**Comment by mbonsma** [comment]
Just a comment that I was also not able to get this code to work for an undirected graph. My workaround was to create a directed graph (`G_dir = G.to_directed()`) and calculate bearings and penalties, and then it all worked great.

**Comment by maxtmng** [comment]
Thank you for the flag and suggestion! It should be fixed with the latest commit.
